import type { District } from '@/types/district.d.ts';

export const DISTRICTS: District[] = [
    { id: 'quan-1', name: 'Quận 1' },
    { id: 'quan-3', name: 'Quận 3' },
    { id: 'quan-4', name: 'Quận 4' },
    { id: 'quan-5', name: 'Quận 5' },
    { id: 'quan-6', name: 'Quận 6' },
    { id: 'quan-7', name: 'Quận 7' },
    { id: 'quan-8', name: 'Quận 8' },
    { id: 'quan-10', name: 'Quận 10' },
    { id: 'quan-11', name: 'Quận 11' },
    { id: 'quan-12', name: 'Quận 12' },
    { id: 'binh-tan', name: 'Quận Bình Tân' },
    { id: 'binh-thanh', name: 'Quận Bình Thạnh' },
    { id: 'go-vap', name: 'Quận Gò Vấp' },
    { id: 'phu-nhuan', name: 'Quận Phú Nhuận' },
    { id: 'tan-binh', name: 'Quận Tân Bình' },
    { id: 'tan-phu', name: 'Quận Tân Phú' },
    { id: 'thu-duc', name: 'Thành phố Thủ Đức' },
    { id: 'binh-chanh', name: 'Huyện Bình Chánh' },
    { id: 'can-gio', name: 'Huyện Cần Giờ' },
    { id: 'cu-chi', name: 'Huyện Củ Chi' },
    { id: 'hoc-mon', name: 'Huyện Hóc Môn' },
    { id: 'nha-be', name: 'Huyện Nhà Bè' },
];
